export const SET_ACTIVE_USER_ID = "SET_ACTIVE_USER_ID";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const SET_TYPING_VALUE = "SET_TYPING_VALUE";
export const SEND_MESSAGE = "SEND_MESSAGE";
export const EDIT_CHAT = "EDIT_CHAT";
export const DELETE_CHAT = "DELETE_CHAT";
